version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
  jenkins:
    image: jenkins/jenkins:lts
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - mynetwork
networks:
  mynetwork: